apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
                namespace: argo
              spec:
                arguments:
                  parameters:
                    - name: number
                    - name: sha
                workflowTemplateRef:
                  name: argocd-diff-github-comment
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.number
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.pull_request.head.sha
              dest: spec.arguments.parameters.1.value
