namespace: argo

resources:
  - https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-minimal.yaml
  - https://raw.githubusercontent.com/crenshaw-dev/argocd-executor-plugin/main/manifests/argocd-executor-plugin-configmap.yaml
  - https://raw.githubusercontent.com/crenshaw-dev/github-executor-plugin/main/github-executor-plugin-configmap.yaml
  - pr-workflowtemplate.yaml
