apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argocd-diff-github-comment
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: get-diff
            template: get-diff
            arguments:
              parameters:
                - name: issue-number
                  value: "{{workflow.parameters.number}}"
                - name: revision
                  value: "{{workflow.parameters.sha}}"
        - - name: comment
            template: comment
            arguments:
              parameters:
                - name: diff
                  value: "{{steps.get-diff.outputs.result}}"
                - name: issue-number
                  value: "{{workflow.parameters.number}}"
    - name: get-diff
      inputs:
        parameters:
          - name: revision
      plugin:
        argocd:
          app:
            diff:
              app:
                name: bootstrap
              revision: "{{inputs.parameters.revision}}"
    - name: comment
      inputs:
        parameters:
          - name: diff
          - name: issue-number
      plugin:
        github:
          issue:
            comment:
              body: |
                ```diff
                {{inputs.parameters.diff}}
                ```
              number: "{{inputs.parameters.issue-number}}"
              owner: crenshaw-dev
              repo: executor-plugins-demo
